// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"zh-CN\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><script src=\"/static/tailwind.js\"></script><script defer src=\"/static/alpine.min.js\"></script><style>\n\t\t\t\t/* 滚动条美化 */\n\t\t\t\t::-webkit-scrollbar { width: 6px; }\n\t\t\t\t::-webkit-scrollbar-track { background: #f1f5f9; }\n\t\t\t\t::-webkit-scrollbar-thumb { background: #94a3b8; border-radius: 3px; }\n\t\t\t</style></head><body class=\"bg-gray-50 min-h-screen\"><nav class=\"bg-white shadow-sm border-b border-gray-200\"><div class=\"max-w-6xl mx-auto px-4 py-3 flex items-center gap-2\"><span class=\"text-2xl\">🔍</span><h1 class=\"text-xl font-bold text-purple-700\">文件去重工具</h1></div></nav><main class=\"max-w-6xl mx-auto px-4 py-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><script>\n\t\t\t\t// 清除内部导航标记（只有新页面加载时才会执行到这里）\n\t\t\t\tsessionStorage.removeItem('internal_nav');\n\n\t\t\t\t// 所有内部链接点击时设置标记，防止触发 shutdown\n\t\t\t\tdocument.addEventListener('click', function(e) {\n\t\t\t\t\tvar a = e.target.closest('a[href]');\n\t\t\t\t\tif (a) {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\tif (new URL(a.href, location.href).origin === location.origin) {\n\t\t\t\t\t\t\t\tsessionStorage.setItem('internal_nav', '1');\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t} catch (_) {}\n\t\t\t\t\t}\n\t\t\t\t});\n\n\t\t\t\twindow.addEventListener('beforeunload', () => {\n\t\t\t\t\tif (sessionStorage.getItem('internal_nav') !== '1') {\n\t\t\t\t\t\tnavigator.sendBeacon('/api/shutdown');\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
